# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - echo Installing some stuff...
      - dotnet --version
      - dotnet --list-sdks
      - dotnet --list-runtimes
      - pwd
      - ls
      - docker -v
  pre_build:
    commands:
      - echo Clean and restore dotnet project
      - cd ./app/src
      - dotnet clean
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -o ../../output
  post_build:
    commands:
      - echo Build completed on `date`
      - cd ../..
      - ls
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  base-directory: app
  files:
    - output/*
    - appspec.yml
    - scripts/*
