################################################################################
#
# Cloud formation parent template
# Author: NGUYEN Daniel
# - Creation of the EC2 Instance with setup of codedeploy agent.
# - Creation of a CodeDeploy setup in AWS.
#
################################################################################


Parameters:

  # codedeploy.cfn.yml parameters

  VPC:
    Description: VPC to create the security group and EC2 instance into
    Type: AWS::EC2::VPC::Id
    AllowedPattern : "^(?:vpc-[0-9a-f]{8}|)$"
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t1.micro, t2.nano, t2.micro, t2.small, t2.medium, t2.large, m1.small,
      m1.medium, m1.large, m1.xlarge, m2.xlarge, m2.2xlarge, m2.4xlarge, m3.medium,
      m3.large, m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge,
      m4.10xlarge, c1.medium, c1.xlarge, c3.large, c3.xlarge, c3.2xlarge, c3.4xlarge,
      c3.8xlarge, c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, g2.2xlarge,
      g2.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge, r3.8xlarge, i2.xlarge,
      i2.2xlarge, i2.4xlarge, i2.8xlarge, d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge,
      hi1.4xlarge, hs1.8xlarge, cr1.8xlarge, cc2.8xlarge, cg1.4xlarge]
  SSHFrom:
    Description: Limit SSH access to bastion hosts to a CIDR IP block
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: 'EC2 Tutorial'
    Description: KeyName

  # ec2Instance.cfn.yml parameters

  CodeDeployDeploymentApplicationName:
    Type: String
    Default: 'DemoApplication'
    Description: The Code Deploy Application Name
  CodeDeployDeploymentGroupName:
    Type: String
    Default: 'DemoFleet'
    Description: The Code Deploy Deployment Group Name
  CodeDeployEnableAutoRollbackConfiguration:
      Description: The Code Deploy AutoRollback Configuration.
      Default: false
      Type: String
      AllowedValues: [true, false]
  EC2TagKey0:
    Type: String
    Default: ec2TagKey0
    Description: The Tag for EC2 and CodeDeploy Deployment Group
  EC2TagValue0:
    Type: String
    Default: ec2TagValue0
    Description: The Tag Value for EC2 and CodeDeploy Deployment Group

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "EC2 Configuration"
        Parameters:
          - VPC
          - InstanceType
          - SSHFrom
          - KeyName
      -
        Label:
          default: "CodeDeploy Configuration"
        Parameters:
          - CodeDeployDeploymentApplicationName
          - CodeDeployDeploymentGroupName
          - CodeDeployEnableAutoRollbackConfiguration
      -
        Label:
          default: "Group Deployment Configuration"
        Parameters:
          - EC2TagKey0
          - EC2TagValue0

Resources:

  EC2InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/ec2Instance.cfn.yml # https://s3.YOUR_REGION.amazonaws.com/YOUR_BUCKET_NAME/123xxxxx.template
      Parameters:
        VPC: !Ref VPC
        InstanceType: !Ref InstanceType
        SSHFrom: !Ref SSHFrom
        KeyName: !Ref KeyName
        EC2TagKey0: !Ref EC2TagKey0
        EC2TagValue0: !Ref EC2TagValue0
      # TimeoutInMinutes: 5

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/codedeploy.cfn.yml # https://YOUR_REGION.amazonaws.com/YOUR_BUCKET_NAME/456xxxxx.template
      Parameters:
        CodeDeployDeploymentApplicationName: !Ref CodeDeployDeploymentApplicationName
        CodeDeployDeploymentGroupName: !Ref CodeDeployDeploymentGroupName
        CodeDeployEnableAutoRollbackConfiguration: !Ref CodeDeployEnableAutoRollbackConfiguration
        EC2TagKey0: !Ref EC2TagKey0
        EC2TagValue0: !Ref EC2TagValue0
      # TimeoutInMinutes: 5


Outputs:

  OutputEC2InstanceStackName:
    Value: !GetAtt EC2InstanceStack.Outputs.OutputEC2InstanceStackName

  OutputCodeDeployStackName:
    Value: !GetAtt CodeDeployStack.Outputs.OutputCodeDeployStackName
