################################################################################
#
# Cloud formation child template
# Author: NGUYEN Daniel
#
# - Creation of a CodeBuild Project Configuration in AWS.
#
################################################################################

AWSTemplateFormatVersion: 2010-09-09

Description: Creation of a CodeBuild Project Configuration in AWS.

Parameters:

  ApplicationName:
    Description: The Application name
    Type: String
    Default: 'DemoApplication'
    ConstraintDescription: must be a valid name
  CodeBuildImage:
    Description: The CodeBuild Image  # https://docs.amazonaws.cn/en_us/codebuild/latest/userguide/build-env-ref-available.html
    Type: String
    Default: aws/codebuild/standard:3.0
    AllowedValues:
    - aws/codebuild/standard:1.0
    - aws/codebuild/standard:2.0
    - aws/codebuild/standard:3.0
    - aws/codebuild/amazonlinux2-x86_64-standard:1.0
    - aws/codebuild/amazonlinux2-x86_64-standard:2.0
    - aws/codebuild/windows-base:1.0
    - aws/codebuild/windows-base:2.0
  CodeBuildComputeType:
    Description: The CodeBuild Compute Type
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
    - BUILD_GENERAL1_SMALL
    - BUILD_GENERAL1_MEDIUM
    - BUILD_GENERAL1_LARGE
  CodeBuildContainerType:
    Description: The CodeBuild Container Type
    Type: String
    Default: LINUX_CONTAINER
    AllowedValues:
    - ARM_CONTAINER
    - LINUX_CONTAINER
    - LINUX_GPU_CONTAINER
  CodeBuildSourceType:
    Description: The CodeBuild Source Type
    Type: String
    Default: CODEPIPELINE
    AllowedValues:
    - CODECOMMIT    # The source code is in an AWS CodeCommit repository.
    - CODEPIPELINE  # The source code settings are specified in the source action of a pipeline in AWS CodePipeline.
    - GITHUB        # The source code is in a GitHub repository.
    - S3            # The source code is in an Amazon Simple Storage Service (Amazon S3) input bucket.
  CodeBuildSourceLocation:
    Description: The CodeBuild Source Location (github repository url, S3 url ...). Useless when CodeBuildSourceType=CODEPIPELINE.
    Type: String
    Default: 'https://github.com/danmgs/AWS.Pipeline.CloudFormation'
  CodeBuildSpec:
    Description: The CodeBuild BuildSpec Path (default is buildspec.yml when let empty)
    Type: String
    Default: ''
  CodeBuildOutputArtifactBucket:
    Description: The CodeBuild Output Artifac S3 tBucket (Useless when CodeBuildSourceType=CODEPIPELINE. This is because AWS CodePipeline manages its build output names instead of AWS CodeBuild.)
    Type: String
    Default: 'com.dnl.cloudformation'
  CodeBuildEnableLogsConfig:
      Description: Enable CloudWatch for the CodeBuild Project.
      Default: ENABLED
      Type: String
      AllowedValues:
      - ENABLED
      - DISABLED

Conditions:
  IsTypeCodePipeline: !Equals [ !Ref CodeBuildSourceType, CODEPIPELINE ] # when using CodePipeline both sourceType, and artifactType must be set to: CODEPIPELINE

Resources:

  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      # RoleName: !Sub "${AWS::StackName}-CodeBuildServiceRole" # runs into errors if too long > 64 chars. let AWS generate the role
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: my-codebuild-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'elasticbeanstalk:*'
                  - 'ec2:*'
                  - 'elasticloadbalancing:*'
                  - 'autoscaling:*'
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'rds:*'
                  - 'sqs:*'
                  - 'ecs:*'
                Resource: '*'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        !If
        - IsTypeCodePipeline
        -
          Type: "CODEPIPELINE" # If type is set to CODEPIPELINE, AWS CodePipeline ignores this value if specified. This is because AWS CodePipeline manages its build output locations instead of AWS CodeBuild.
        -
          Location: !Ref CodeBuildOutputArtifactBucket
          Type: "S3"
      Name: !Ref ApplicationName
      Description: !Sub CodeBuild Project generated by Cloud Formation Stack ${AWS::StackName}
      Source:
        Location:
          !If
          - IsTypeCodePipeline
          -
            !Ref "AWS::NoValue" # For source code settings that are specified in the source action of a pipeline in AWS CodePipeline, location should not be specified. If it is specified, AWS CodePipeline ignores it. This is because AWS CodePipeline uses the settings in a pipeline's source action instead of this value.
          -
            !Ref CodeBuildSourceLocation # For source code in a GitHub repository, the HTTPS clone URL to the repository that contains the source and the build spec.
        Type: !Ref CodeBuildSourceType
        BuildSpec: !Ref CodeBuildSpec
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildImage
        Type: !Ref CodeBuildContainerType
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
      LogsConfig:
        CloudWatchLogs:
          # GroupName: !Sub ${AWS::StackName}-${ApplicationName}
          Status: !Ref CodeBuildEnableLogsConfig
      ServiceRole: !Ref CodeBuildServiceRole

Outputs:

  ApplicationName:
    Description: The Application Name
    Value: !Ref ApplicationName

  CodeBuildProject:
    Description: The CodeBuild Project
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub ${AWS::StackName}-CodeBuildProject

  CodeBuildProjectArn:
    Description: The CodeBuild Project Arn
    Value: !GetAtt CodeBuildProject.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CodeBuildProjectArn
