################################################################################
#
# Cloud formation child template
# Author: NGUYEN Daniel
#
# - Creation of a table in dynamodb in AWS for the website.
#
################################################################################

AWSTemplateFormatVersion: 2010-09-09

Description: Creation of a table DynamoDB in AWS.

Parameters:

  ApplicationName:
    Description: The Application name
    Type: String
    MinLength: '1'
    Default: 'DemoApplication'
    ConstraintDescription: must be a valid name
  EnvironmentName:
    Type: String
    Default: production
    Description: "A friendly environment name that will be used for namespacing all cluster resources. Example: staging, qa, or production"
  TableName:
    Description: The DynamoDB Table Name
    Type: String
    MinLength: '1'
    Default: 'Users'
    ConstraintDescription: must be a valid name
  BillingMode:
      Description: The Billing Mode
      Default: PROVISIONED
      Type: String
      AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST
  ReadCapacityUnits:
    Description: The Read Capacity Units (RCU)
    Type: Number
    Default: 5
    ConstraintDescription: must be a valid number
  WriteCapacityUnits:
    Description: The Write Capacity Units (WCU)
    Type: Number
    Default: 5
    ConstraintDescription: must be a valid number

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - ApplicationName
          - EnvironmentName
      -
        Label:
          default: "Table General Settings"
        Parameters:
          - Table
      -
        Label:
          default: "Table Capacity Settings"
        Parameters:
          - BillingMode
          - ReadCapacityUnits
          - WriteCapacityUnits

Conditions:
  IsDbAutoScaled: !Equals [ !Ref BillingMode, PAY_PER_REQUEST ]

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: !Ref BillingMode
      ProvisionedThroughput: # If you set BillingMode as PROVISIONED, you must specify this property. If you set BillingMode as PAY_PER_REQUEST, you cannot specify this property.
        !If
        - IsDbAutoScaled
        -
          !Ref "AWS::NoValue"
        -
          ReadCapacityUnits: !Ref ReadCapacityUnits
          WriteCapacityUnits: !Ref WriteCapacityUnits
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
        - Key: EnvironmentName
          Value: !Ref EnvironmentName

Outputs:

  Table:
    Description: The DynamoDB Table Arn
    Value: !GetAtt DynamoDBTable.Arn
    