version: 0.0
os: linux
files:
  - source: /output
    destination: /usr/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 200
      runas: root
  BeforeInstall:
    - location: scripts/clean_destination.sh
      timeout: 200
      runas: root
    - location: scripts/configure_server.sh
      timeout: 200
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 100
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh
      timeout: 200
      runas: root
