version: 0.0
os: linux
files:
  - source: /output
    destination: /usr/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 200
      runas: root
  BeforeInstall:
    - location: scripts/clean_destination
      timeout: 200
      runas: root
  AfterInstall:
    - location: scripts/afterInstall
      timeout: 100
      runas: root
